language: cpp
compiler: gcc

os: linux

env:
  matrix:
    - BUILD_TYPE=Debug CXXFLAGS="--coverage -fsanitize=address -std=c++17" LDFLAGS="--coverage -fsanitize=address" GCOV="--gcov-tool gcov-7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - lcov

script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build . --target
  - make
  - ctest

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info 
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"