language: cpp
compiler: gcc

os: linux

env:
  matrix:
    - BUILD_TYPE=Debug CXXFLAGS="--coverage -fsanitize=address -std=c++17" LDFLAGS="--coverage -fsanitize=address" GCOV="--gcov-tool gcov-7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - lcov

script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build . --target neat
  
  after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
