language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - lcov

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build . --target
  - make
  - ctest

after_success:
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info 
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"